common:
  lid_topic:  "/velodyne_points"
  imu_topic:  "/imu/data_raw"
  time_sync_en: false         # ONLY turn on when external time synchronization is really not possible

preprocess:
  lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR,
  scan_line: 64
  blind: 4
  scan_rate: 10
  timestamp_unit: 2
  time_scale: 1e-3             # 兼容不同数据集的时间单位，仅对Velodyne LiDAR(lidar_type=2)生效

mapping:
  acc_cov: 0.1
  gyr_cov: 0.1
  b_acc_cov: 6.4356659353532566e-05
  b_gyr_cov: 3.5640318696367613e-05
  fov_degree: 180
  det_range: 100.0
  extrinsic_est_en:  true      # true: enable the online estimation of IMU-LiDAR extrinsic,
  extrinsic_T: [ -8.086759e-01, 3.195559e-01, -7.997231e-01]
  extrinsic_R: [9.999976e-01, 7.553071e-04, -2.035826e-03, -7.854027e-04, 9.998898e-01, -1.482298e-02, 2.024406e-03, 1.482454e-02, 9.998881e-01]

publish:
  path_publish_en: false
  scan_publish_en: true       # false: close all the point cloud output
  scan_effect_pub_en: true    # true: publish the pointscloud of effect point
  dense_publish_en: false       # false: low down the points number in a global-frame point clouds scan.
  scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

path_save_en: true                 # 保存轨迹，用于精度计算和比较

pcd_save:
  pcd_save_en: true
  interval: -1                 # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
